### ISSUE TITLE
Errorback argument order

### ISSUE THREAD

**Issue by bcomnes** [paypal/seif-protocol#10]
Maybe this is a dumb question or I am missing something, but your callbacks error argument comes last in a number APIs:

e.g.

```
function callback(party, error){
```

Given the modern popularity of error first 'errorbacks' from nodejs's API (e.g. `cb(err, stuff)`,  is there a reason error last errorbacks were chosen for this project?   It seems to be going against the grain in this day and age if its purely for stylistic preference.

**Comment by douglascrockford** [comment]
Node got it wrong. The Seif Project is about making things radically better, not preserving past mistakes. There are not many projects where you get to do that.

**Comment by mreinstein** [comment]
Why is it wrong?

**Comment by bcomnes** [comment]
Do you (or anyone) recommend any discussion on why error last callbacks are preferred/better?  Its not immediately obvious to me why one or the other is better outside of the convention.
