### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by 4thex** [paypal/seif-protocol#11]
Question: A party is initialized with a username and a password to generate a globally unique id. What happens if a user wants to change this password? I assume that it would mean that the party would need to be re-initiated. How does the server know that this is the same party? Is that communication outside the scope of this protocol?
Moreover, how does the server side know that the client party is who they claim to be?

**Comment by douglascrockford** [comment]
The username and password are not used to generate the id. They are used to protect the private key. This is outside of the protocol.
